### PR TITLE
[FIX] upgraded to RC2

### PR DESCRIPTION
**Pull request by Tazer**
Hello,

I want to use IdentityModel etc for my new project in RC2. 

So started the work on converting it to RC2. Started with this project cause IdentityServer4.AccessTokenValidation was dependent on this one.

Just close this one if you doing the work already :)

### CODE REVIEW

**Comment by Tazer** [comment]
Someone needs to help me fix the build with psake for RC2 tho :)
Error: 2016-05-17 13:41:32:
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: global.json doesn't contain sdk info
  rmation.

**Comment by Tazer** [comment]
Guess we/I can look at https://github.com/c3-ls/ServiceFabric-Http/blob/master/build-definition.ps1 and see how they have done it ?

**Comment by Tazer** [comment]
@leastprivilege :  Got everything working on RC2 , build.cmd is working and all tests are passing. 

The only thing that I'm not sure about is how to run the tests for full framework vs core.

**Comment by leastprivilege** [comment]
cool! We are in the process right now of upgrading the code. Not quite there yet - will get back to you.

thanks!

**Comment by Tazer** [comment]
Great! Looking forward to that! :) And if you need any help I may be able to assist :)

**Comment by leastprivilege** [comment]
great work!

I wanted to go through the process myself - but used your code as a cheat sheet ;) thanks!

**Comment by Tazer** [comment]
No worries! 

Looking forward for the RC2 version! :+1:

**Pull request closed without merging**
